### ISSUE TITLE
Unable to Access Backend After Deployment with Ingress Enabled

### ISSUE THREAD

**Issue by CDiezRodriguez** [eclipse-tractusx/industry-core-hub#189]
### Current Behavior
After deploying the Backend with ingress enabled via the Helm chart, accessing the service results in a 502 Bad Gateway error.

### Expected Behavior
The service should be accessible via the configured ingress host.

### Steps To Reproduce
1. Modify the values.yaml file to enable ingress:
```yaml
  ingress:
    enabled: true
    hosts:
      - host: "ichub.backend.tx.test"
```
2. Update the Helm chart dependencies: `helm dep up`
3. Install the chart with the modified values: `helm install ichub -f ./values.yaml . --namespace ichub`
4. Try to access: `http://ichub.backend.tx.test/docs`
5. Observe the error: `502 Bad Gateway`
